

// const logos = [
//   { id: 1, src: '../logos/ARI.png', title: 'ARI' },
//   { id: 2, src: '../logos/ATL.png', title: 'ATL' },
//   { id: 3, src: '../logos/BAL.png', title: 'BAL' },
//   { id: 4, src: '../logos/BUF.png', title: 'BUF' },
//   { id: 5, src: '../logos/CAR.png', title: 'CAR' },
//   { id: 6, src: '../logos/CHI.png', title: 'CHI' },
//   { id: 7, src: '../logos/CIN.png', title: 'CIN' },
//   { id: 8, src: '../logos/CLE.png', title: 'CLE' },
//   { id: 9, src: '../logos/DAL.png', title: 'DAL' },
//   { id: 10, src: '../logos/DEN.png', title: 'DEN' },
//   { id: 11, src: '../logos/DET.png', title: 'DET' },
//   { id: 12, src: '../logos/GB.png', title: 'GB' },
//   { id: 13, src: '../logos/HOU.png', title: 'HOU' },
//   { id: 14, src: '../logos/IND.png', title: 'IND' },
//   { id: 15, src: '../logos/JAX.png', title: 'JAX' },
//   { id: 16, src: '../logos/KC.png', title: 'KC' },
//   { id: 29, src: '../logos/LAC.png', title: 'LAC' },
//   { id: 32, src: '../logos/LAR.png', title: 'LAR' },
//   { id: 25, src: '../logos/LV.png', title: 'LV' },
//   { id: 19, src: '../logos/MIA.png', title: 'MIA' },
//   { id: 20, src: '../logos/MIN.png', title: 'MIN' },
//   { id: 21, src: '../logos/NE.png', title: 'NE' },
//   { id: 22, src: '../logos/NO.png', title: 'NO' },
//   { id: 23, src: '../logos/NYG.png', title: 'NYG' },
//   { id: 24, src: '../logos/NYJ.png', title: 'NYJ' },
//   { id: 26, src: '../logos/PHI.png', title: 'PHI' },
//   { id: 28, src: '../logos/PIT.png', title: 'PIT' },
//   { id: 30, src: '../logos/SEA.png', title: 'SEA' },
//   { id: 31, src: '../logos/SF.png', title: 'SF' },
//   { id: 33, src: '../logos/TB.png', title: 'TB' },
//   { id: 34, src: '../logos/TEN.png', title: 'TEN' },
//   { id: 35, src: '../logos/WAS.png', title: 'WAS' },
// ];

const logos = {
  1 : '../logos/ARI.png',
  2 : '../logos/ATL.png',
  3 : '../logos/BAL.png',
  4 : '../logos/BUF.png',
  5 : '../logos/CAR.png',
  6 : '../logos/CHI.png',
  7 : '../logos/CIN.png',
  8 : '../logos/CLE.png',
  9 : '../logos/DAL.png',
  10 : '../logos/DEN.png',
  11 : '../logos/DET.png',
  12 : '../logos/GB.png',
  13 : '../logos/HOU.png',
  14 : '../logos/IND.png',
  15 : '../logos/JAX.png',
  16 : '../logos/KC.png',
  29 : '../logos/LAC.png',
  32 : '../logos/LAR.png',
  25 : '../logos/LV.png', 
  19 : '../logos/MIA.png',
  20 : '../logos/MIN.png',
  21 : '../logos/NE.png', 
  22 : '../logos/NO.png',
  23 : '../logos/NYG.png',
  24 : '../logos/NYJ.png',
  26 : '../logos/PHI.png',
  28 : '../logos/PIT.png',
  30 : '../logos/SEA.png',
  31 : '../logos/SF.png', 
  33 : '../logos/TB.png', 
  34 : '../logos/TEN.png',
  35 : '../logos/WAS.png',
};

export default logos;